name: Ideal Wild
favicon: null
layout_spectrum: 0.4726
typography_spectrum: 0.98728
title: Ideal Wild
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f1eef1'
    - '#d4d2db'
    - '#c4aea5'
    - '#31382f'
    - '#68604e'
  brandStrength: 1
  lightness: 0.8110506031662226
  saturation: 0.5
  rhythmicContrast: 0.8734867228195071
purpose: []
