name: Ideal Wild
favicon: null
layout_spectrum: 0.7544
typography_spectrum: 0.98728
title: Ideal Wild
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#23221f'
    - '#cbccce'
    - '#40413d'
    - '#8a8f92'
    - '#5f5f5d'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
